### ISSUE TITLE
on CRM 2015 > missing attribute 'canbeentityreference'

### ISSUE THREAD

**Issue by jellevervloessem** [santoshCRM/Export-Security-Role#9]
When I open a securityrole from CRM2015, I get the following error:

> Exception details: 
> ErrorCode: 0x80041103
> Message: 'Privilege' entity doesn't contain attribute with Name = 'canbeentityreference'.
> TimeStamp: 2021-01-07T12:06:43.0129229Z

When opening another securityrole from CRM2015, I get this error:
"An error occurred when parsing EntityName. Line 1, position 294."

> ************* Exception Text **************
> System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 294.
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.ParseEntityName()
>    at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
>    at System.Xml.XmlTextReaderImpl.ParseAttributes()
>    at System.Xml.XmlTextReaderImpl.ParseElement()
>    at System.Xml.XmlTextReaderImpl.ParseElementContent()
>    at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
>    at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
>    at System.Xml.XmlDocument.Load(XmlReader reader)
>    at RoleDocumenter.RoleDocumenterCtl.CreateXml(String fetchXml, String pagingCookie, Int32 pageNumber, Int32 fetchCount)
>    at RoleDocumenter.RoleDocumenterCtl.RolePrivileges(SecurityRole selectedRole)
>    at RoleDocumenter.RoleDocumenterCtl.<>c__DisplayClass92_0.<GetRole>b__0(BackgroundWorker w, DoWorkEventArgs e)
>    at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
>    at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by LinkeD365** [comment]
@jellevervloessem Hhhm. I don't have access to a 2015 environment. If it is OK, contact me via linked365.blog to go via email and arrange for you to help me?

**Comment by ZaarourOmar** [comment]
I got the same problem with this error, the solution for me was to install the plugin code, comment that property from the GetRole fetchxml and it worked fine. Looks like older vesions of CRM are missing this property from the roleprivilage table.

**Comment by LinkeD365** [comment]
Thanks, @ZaarourOmar I know how to fix this, will be done soon, unless you want to do a pull request?

**Comment by matthew-yee** [comment]
same issue, In the same process of applying the manual fix, thanks for the insight.
